/*
 * This source file was generated by the Gradle 'init' task
 */
package midterm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CompleteBinaryTreeTest {
    @Test
    void insert() {
        CompleteBinaryTree tree = new CompleteBinaryTree();
        tree.insert(1);
        tree.insert(2);
        tree.insert(3);

        assertEquals(tree.toString(), "1 2 3 ", "Inserting 1, 2, 3 should return '1 2 3'");
    }

    @Test
    void insert2() {
        CompleteBinaryTree tree = new CompleteBinaryTree();
        tree.insert(1);
        tree.insert(2);
        tree.insert(3);
        tree.insert(4);

        assertEquals(tree.toString(), "1 2 3 4 ", "Inserting 1, 2, 3, 4 should return '1 2 3 4'");
    }

    @Test
    void delete() {
        CompleteBinaryTree tree = new CompleteBinaryTree();
        tree.insert(1);
        tree.insert(2);
        tree.insert(3);
        tree.insert(4);
        
        assertEquals(tree.toString(), "1 2 3 4 ", "Should return '1 2 3 4'");

        tree.delete(3);

        assertEquals(tree.toString(), "1 2 4 ", "Deleting 3 should return '1 2 4'");
    }

    @Test
    void isMaxHeap(){
        CompleteBinaryTree tree = new CompleteBinaryTree();
        tree.insert(10);
        tree.insert(9);
        tree.insert(8);
        tree.insert(7);
        tree.insert(6);
        assertTrue(tree.question1(), "Tree1 should satisfy max-heap property");
    }

    void isMaxHeap2(){
        CompleteBinaryTree tree = new CompleteBinaryTree();
        tree.insert(10);
        tree.insert(20); //break ahi thase 
        tree.insert(8);
        tree.insert(7);
        tree.insert(6);
        assertTrue(tree.question1(), "Tree should satisfy max-heap property");
    }

    @Test
    //incomplete 
    void cloneTree(){
        CompleteBinaryTree tree = new CompleteBinaryTree();
        tree.insert(15);
        tree.insert(10);
        tree.insert(20); 
        tree.insert(5);
        tree.insert(12);
        tree.insert(18);
        tree.insert(30);

        //should match the original tree 

    }

}